AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Example...


Resources:
  PublishQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: PublishQueue

  EventTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: EventTopic

  EchoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: EchoFunction
      CodeUri: functions/echo/
      Timeout: 5
      AutoPublishAlias: live
      Handler: app.lambda_handler
      Runtime: python3.9
      MemorySize: 128
      Tracing: Active

  ReceiverFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ReceiverFunction
      CodeUri: functions/receiver/
      Timeout: 5
      AutoPublishAlias: live
      Handler: app.lambda_handler
      Runtime: python3.9
      MemorySize: 128
      Tracing: Active
      Environment:
        Variables:
          ACK_STATE_MACHINE_ARN: !Ref EnrichmentStateMachineExpress2
          RESPONSE_STATE_MACHINE_ARN: !Ref EnrichmentStateMachineExpress3
      Policies:
        - StepFunctionsExecutionPolicy:
            StateMachineName: !GetAtt EnrichmentStateMachineExpress2.Name
        - StepFunctionsExecutionPolicy:
            StateMachineName: !GetAtt EnrichmentStateMachineExpress3.Name
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt PublishQueue.Arn
            BatchSize: 1

  EnrichmentStateMachineStandard:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: EnrichmentStateMachineStandard
      Type: STANDARD
      DefinitionUri: statemachine/enrichment-template-standard.asl.json
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt EnrichmentStateMachineStandardCloudWatchLogsGroup.Arn
        IncludeExecutionData: True
        Level: ALL # ALL | ERROR | FATAL | OFF
      Tracing:
        Enabled: true
      DefinitionSubstitutions:
        PublishQueue: !Ref PublishQueue
        EventTopic: !Ref EventTopic
        EchoFunction: !Ref EchoFunction
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref EchoFunction
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt EventTopic.TopicName
        - SQSSendMessagePolicy:
            QueueName: !GetAtt PublishQueue.QueueName
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: # see https://docs.aws.amazon.com/step-functions/latest/dg/cw-logs.html
                - logs:CreateLogDelivery
                - logs:GetLogDelivery
                - logs:UpdateLogDelivery
                - logs:DeleteLogDelivery
                - logs:ListLogDeliveries
                - logs:PutResourcePolicy
                - logs:DescribeResourcePolicies
                - logs:DescribeLogGroups
              Resource: "*"

  EnrichmentStateMachineStandardCloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /rs/rs-enrichment-service-standard
      RetentionInDays: 7

  EnrichmentStateMachineExpress1:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: EnrichmentStateMachineExpress1
      Type: EXPRESS
      DefinitionUri: statemachine/enrichment-template-express-1.asl.json
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt EnrichmentStateMachineExpressCloudWatchLogsGroup.Arn
        IncludeExecutionData: True
        Level: ALL # ALL | ERROR | FATAL | OFF
      Tracing:
        Enabled: true
      DefinitionSubstitutions:
        PublishQueue: !Ref PublishQueue
        EventTopic: !Ref EventTopic
        EchoFunction: !Ref EchoFunction
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref EchoFunction
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt EventTopic.TopicName
        - SQSSendMessagePolicy:
            QueueName: !GetAtt PublishQueue.QueueName
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: # see https://docs.aws.amazon.com/step-functions/latest/dg/cw-logs.html
                - logs:CreateLogDelivery
                - logs:GetLogDelivery
                - logs:UpdateLogDelivery
                - logs:DeleteLogDelivery
                - logs:ListLogDeliveries
                - logs:PutResourcePolicy
                - logs:DescribeResourcePolicies
                - logs:DescribeLogGroups
              Resource: "*"

  EnrichmentStateMachineExpress2:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: EnrichmentStateMachineExpress2
      Type: EXPRESS
      DefinitionUri: statemachine/enrichment-template-express-2.asl.json
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt EnrichmentStateMachineExpressCloudWatchLogsGroup.Arn
        IncludeExecutionData: True
        Level: ALL # ALL | ERROR | FATAL | OFF
      Tracing:
        Enabled: true
      DefinitionSubstitutions:
        EventTopic: !Ref EventTopic
        EchoFunction: !Ref EchoFunction
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref EchoFunction
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt EventTopic.TopicName
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: # see https://docs.aws.amazon.com/step-functions/latest/dg/cw-logs.html
                - logs:CreateLogDelivery
                - logs:GetLogDelivery
                - logs:UpdateLogDelivery
                - logs:DeleteLogDelivery
                - logs:ListLogDeliveries
                - logs:PutResourcePolicy
                - logs:DescribeResourcePolicies
                - logs:DescribeLogGroups
              Resource: "*"

  EnrichmentStateMachineExpress3:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: EnrichmentStateMachineExpress3
      Type: EXPRESS
      DefinitionUri: statemachine/enrichment-template-express-3.asl.json
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt EnrichmentStateMachineExpressCloudWatchLogsGroup.Arn
        IncludeExecutionData: True
        Level: ALL # ALL | ERROR | FATAL | OFF
      Tracing:
        Enabled: true
      DefinitionSubstitutions:
        EventTopic: !Ref EventTopic
        EchoFunction: !Ref EchoFunction
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref EchoFunction
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt EventTopic.TopicName
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: # see https://docs.aws.amazon.com/step-functions/latest/dg/cw-logs.html
                - logs:CreateLogDelivery
                - logs:GetLogDelivery
                - logs:UpdateLogDelivery
                - logs:DeleteLogDelivery
                - logs:ListLogDeliveries
                - logs:PutResourcePolicy
                - logs:DescribeResourcePolicies
                - logs:DescribeLogGroups
              Resource: "*"

  EnrichmentStateMachineExpressCloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /rs/rs-enrichment-service-express
      RetentionInDays: 7
